version: '3.8'

services:
  usgasvisualization:
    build: .
    ports:
      - "3838:3838"
    volumes:
      - ./app.R:/srv/shiny-server/app.R
      - ./renv.lock:/srv/shiny-server/renv.lock
    environment:
      - SHINY_LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3838/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - usgasvisualization
  #   restart: unless-stopped